site_name: SDMX Technical Documentation
site_description: Statistical Data and Metadata eXchange
site_url: https://HMS-Analytical-Software.github.io/sdmx-technical-documentation
strict: true
copyright: '<a href="https://www.analytical-software.de/en/legal-disclosure/">HMS Analytical Software Imprint</a>'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: blue
    accent: orange
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: orange
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: orange
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    # - announce.dismiss
    - navigation.tabs
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    # - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: 'media/logos/SDMX-logo.png'
  favicon: 'media/logos/favicon.png'

repo_name: HMS-Analytical-Software/sdmx-technical-documentation
repo_url: https://github.com/HMS-Analytical-Software/sdmx-technical-documentation
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
- Overview:
  - Welcome to SDMX: index.md
- Framework:
  - Release History: framework/framework-release-history.md
  - Introduction: framework/framework-introduction.md
  - Change History: framework/framework-change-history.md
  - Processes and Business Scope: framework/framework-processes-and-business-scope.md
  - The SDMX Information Model: framework/framework-the-sdmx-information-model.md
  - The SDMX Transmission Formats: framework/framework-the-sdmx-transmission-formats.md
  - Dependencies on SDMX content-oriented guidelines: framework/framework-dependencies-on-sdmx-content-oriented-guidelines.md
  - Validation and Transformation Language: framework/framework-validation-and-transformation-language.md
- Information Models:
  - Information Model: information_model.md
- Registry Specification:
  - Registry Specification: registry_specification_logical_interfaces.md
- Technical Notes:
  - Technical Notes: technical_notes.md
- Transmission Formats:
  - REST API: rest_api.md
  - SDMX-ML: sdmx_ml.md
  - SDMX-JSON: sdmx_json.md
  - SDMX-CSV: sdmx_csv.md

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true

plugins:
# - social
- mike:
    alias_type: symlink
    canonical_version: latest
- search
- exclude:
    glob:
    - theme/announce.html
    - plugins/*
    - __pycache__/*
- enumerate-headings:
    toc_depth: 0
    strict: true
    increment_across_pages: true
    include:
      - "*"
    exclude:
      - index.md
- i18n:
    docs_structure: suffix
    reconfigure_material: true
    languages:
      - locale: en
        name: English
        build: true
        default: true
      - locale: de
        name: German
        build: true