site_name: SDMX Technical Documentation
site_description: Statistical Data and Metadata eXchange
site_url: https://HMS-Analytical-Software.github.io/sdmx-technical-documentation
strict: true
copyright: '<a href="https://www.analytical-software.de/en/legal-disclosure/">HMS Analytical Software Imprint</a>'

theme:
  name: 'material'
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: indigo
    accent: orange
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: orange
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: orange
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    # - announce.dismiss
    - navigation.tabs
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    # - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: 'media/logos/SDMX-logo.png'
  favicon: 'media/logos/favicon.png'

repo_name: HMS-Analytical-Software/sdmx-technical-documentation
repo_url: https://github.com/HMS-Analytical-Software/sdmx-technical-documentation
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
- Getting Started:
  - Welcome to SDMX: index.md
- Framework:
  - Release History: framework/framework-release-history.md
  - Introduction: framework/framework-introduction.md
  - Change History: framework/framework-change-history.md
  - Processes and Business Scope: framework/framework-processes-and-business-scope.md
  - The SDMX Information Model: framework/framework-the-sdmx-information-model.md
  - The SDMX Transmission Formats: framework/framework-the-sdmx-transmission-formats.md
  - Dependencies on SDMX content-oriented guidelines: framework/framework-dependencies-on-sdmx-content-oriented-guidelines.md
  - Validation and Transformation Language: framework/framework-validation-and-transformation-language.md
- Information Model:
  - Change History: information_model/0_change_history.md
  - Introduction: information_model/0_Introduction.md
  - Actors and Use Cases: information_model/1_Actors_and_Use_Cases.md
  - SDMX Base Package: information_model/2_SDMX_Base_Package.md
  - Specific Item Schemes: information_model/3_Specific_Item_Schemes.md
  - Data Structure Definition and Dataset: information_model/4_Data_Structure_Definition_and_Dataset.md
  - Cube: information_model/5_Cube.md
  - Metadata Structure Definition and Metadata Set: information_model/6_Metadata_Structure_Definition_and_Metadata_Set.md
  - Hierarchy: information_model/7_Hierarchy.md
  - Structure Map: information_model/8_Structure_Map.md
  - RepresentationMap: information_model/9_RepresentationMap.md
  - ItemSchemeMap: information_model/10_ItemSchemeMap.md
  - Constraints: information_model/11_Constraints.md
  - Data Provisioning: information_model/12_Data_Provisioning.md
  - Process: information_model/13_Process.md
  - Validation and Transformation Language: information_model/14_Validation_and_Transformation_Language.md
  - Appendix 1 A Short Guide to UML in the SDMX Information Model: information_model/15_Appendix_1:_A_Short_Guide_to_UML_in_the_SDMX_Information_Model.md
- Registry Specification and Logical Interfaces:
  - Registry Specification: registry_specification_logical_interfaces/registry_specification_logical_interfaces.md
- Technical Notes:
  - Technical Notes: technical_notes/technical_notes.md
- REST API:
  - REST API: rest_api/rest_api.md
- Transmission Formats:
  - SDMX-ML: transmission_formats/sdmx_ml.md
  - SDMX-JSON: transmission_formats/sdmx_json.md
  - SDMX-CSV: transmission_formats/sdmx_csv.md
- Go To sdmx.org: "https://sdmx.org/"

markdown_extensions:
- tables
- toc:
    permalink: true
    title: On this page
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.blocks.caption


plugins:
# - social
- mike:
    alias_type: symlink
    canonical_version: latest
- search
- exclude:
    glob:
    - theme/announce.html
    - plugins/*
    - __pycache__/*
# - enumerate-headings:
#     toc_depth: 0
#     strict: true
#     increment_across_pages: true
#     include:
#       - "*"
#     exclude:
#       - index.md
- i18n:
    docs_structure: suffix
    reconfigure_material: true
    languages:
      - locale: en
        name: English
        build: true
        default: true
      - locale: de
        name: German
        build: true