site_name: SDMX Technical Documentation
site_description: Statistical Data and Metadata eXchange
site_url: https://HMS-Analytical-Software.github.io/sdmx-technical-documentation
strict: true

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: blue
    accent: orange
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: orange
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: orange
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: 'media/logos/SDMX-logo.png'
  favicon: 'media/logos/favicon.png'

repo_name: HMS-Analytical-Software/sdmx-technical-documentation
repo_url: https://github.com/HMS-Analytical-Software/sdmx-technical-documentation
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
- Overview:
  - Welcome to SDMX: index.md
  - Framework: framework.md
- Information Models:
  - Information Model: information_model.md
- Registry Specification:
  - Registry Specification: registry_specification_logical_interfaces.md
- Technical Notes:
  - Technical Notes: technical_notes.md
- Transmission Formats:
  - REST API: rest_api.md
  - SDMX-ML: sdmx_ml.md
  - SDMX-JSON: sdmx_json.md
  - SDMX-CSV: sdmx_csv.md
# - Get Started:
#   - Welcome to Pydantic: index.md
#   - Why use Pydantic: why.md
#   - Help with Pydantic: help_with_pydantic.md
#   - Installation: install.md
#   - Migration Guide: migration.md
#   - Version Policy: version-policy.md
#   - Contributing: contributing.md
#   - Changelog: changelog.md
# - Concepts:
#   - Models: concepts/models.md
#   - Fields: concepts/fields.md
#   - JSON Schema: concepts/json_schema.md
#   - JSON: concepts/json.md
#   - Types: concepts/types.md
#   - Unions: concepts/unions.md
#   - Alias: concepts/alias.md
#   - Configuration: concepts/config.md
#   - Serialization: concepts/serialization.md
#   - Validators: concepts/validators.md
#   - Dataclasses: concepts/dataclasses.md
#   - Forward Annotations: concepts/forward_annotations.md
#   - Strict Mode: concepts/strict_mode.md
#   - Type Adapter: concepts/type_adapter.md
#   - Validation Decorator: concepts/validation_decorator.md
#   - Conversion Table: concepts/conversion_table.md
#   - Settings Management: concepts/pydantic_settings.md
#   - Performance: concepts/performance.md
#   - Experimental: concepts/experimental.md
# - API Documentation:
#   - Pydantic:
#     - BaseModel: api/base_model.md
#     - RootModel: api/root_model.md
#     - Pydantic Dataclasses: api/dataclasses.md
#     - TypeAdapter: api/type_adapter.md
#     - Validate Call: api/validate_call.md
#     - Fields: api/fields.md
#     - Aliases: api/aliases.md
#     - Configuration: api/config.md
#     - JSON Schema: api/json_schema.md
#     - Errors: api/errors.md
#     - Functional Validators: api/functional_validators.md
#     - Functional Serializers: api/functional_serializers.md
#     - Standard Library Types: api/standard_library_types.md
#     - Pydantic Types: api/types.md
#     - Network Types: api/networks.md
#     - Version Information: api/version.md
#     - Annotated Handlers: api/annotated_handlers.md
#     - Experimental: api/experimental.md
#   - Pydantic Core:
#     - pydantic_core: api/pydantic_core.md
#     - pydantic_core.core_schema: api/pydantic_core_schema.md
#   - Pydantic Settings: api/pydantic_settings.md
#   - Pydantic Extra Types:
#     - Color: api/pydantic_extra_types_color.md
#     - Country: api/pydantic_extra_types_country.md
#     - Payment: api/pydantic_extra_types_payment.md
#     - Phone Numbers: api/pydantic_extra_types_phone_numbers.md
#     - Routing Numbers: api/pydantic_extra_types_routing_numbers.md
#     - Coordinate: api/pydantic_extra_types_coordinate.md
#     - Mac Address: api/pydantic_extra_types_mac_address.md
#     - ISBN: api/pydantic_extra_types_isbn.md
#     - Pendulum: api/pydantic_extra_types_pendulum_dt.md
#     - Currency: api/pydantic_extra_types_currency_code.md
#     - Language: api/pydantic_extra_types_language_code.md
#     - Script Code: api/pydantic_extra_types_script_code.md
#     - Semantic Version: api/pydantic_extra_types_semantic_version.md
#     - Timezone Name: api/pydantic_extra_types_timezone_name.md
#     - ULID: api/pydantic_extra_types_ulid.md
# - Internals:
#   - Architecture: internals/architecture.md
#   - Resolving Annotations: internals/resolving_annotations.md
# - Examples:
#   - Validating File Data: examples/files.md
#   - Web and API Requests: examples/requests.md
#   - Queues: examples/queues.md
#   - Databases: examples/orms.md
#   - Custom Validators: examples/custom_validators.md
# - Error Messages:
#   - Error Handling: errors/errors.md
#   - Validation Errors: errors/validation_errors.md
#   - Usage Errors: errors/usage_errors.md
# - Integrations:
#   - Pydantic Logfire: integrations/logfire.md
#   - LLMs: integrations/llms.md
#   - Dev Tools:
#     - Mypy: integrations/mypy.md/.
#     - PyCharm: integrations/pycharm.md
#     - Hypothesis: integrations/hypothesis.md
#     - Visual Studio Code: integrations/visual_studio_code.md
#     - datamodel-code-generator: integrations/datamodel_code_generator.md
#     - devtools: integrations/devtools.md
#     - Rich: integrations/rich.md
#     - Linting: integrations/linting.md
#     - Documentation: integrations/documentation.md
#   - Production Tools:
#     - AWS Lambda: integrations/aws_lambda.md
# - Blog: https://blog.pydantic.dev/
# - Pydantic People: pydantic_people.md

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true

plugins:
# - social
- mike:
    alias_type: symlink
    canonical_version: latest
  # llmstxt must come after the mike plugin:
- llmstxt:
    enabled: !ENV [CI, false]
    full_output: llms-full.txt
    markdown_description: |-
      Pydantic is the most widely used data validation library for Python.
      Fast and extensible, Pydantic plays nicely with your linters/IDE/brain.
      Define how data should be in pure, canonical Python 3.9+; validate it with Pydantic.
    sections:
      Concepts documentation:
        - concepts/*.md
      API documentation:
        - api/*.md
      Internals:
        - internals/*.md
      Optional:
        - errors/*.md
        - examples/*.md
        - integrations/*.md
- search
- exclude:
    glob:
    - theme/announce.html
    - plugins/*
    - __pycache__/*
- enumerate-headings:
    toc_depth: 0
    strict: true
    increment_across_pages: true
    include:
      - "*"
    exclude:
      - index.md
      # - another_page.md
    # restart_increment_after:
      # - second_section.md
# - mkdocstrings:
#     handlers:
#       python:
#         paths: [.]  # see also: build-docs.sh
#         options:
#           members_order: source
#           separate_signature: true
#           filters: ["!^_"]
#           docstring_options:
#             ignore_init_summary: true
#           merge_init_into_class: true
#           show_signature_annotations: true
#           signature_crossrefs: true
#         import:
#           - url: https://docs.python.org/3/objects.inv
#             domains: [py, std]
# - redirects:
    # redirect_maps: