name: docs-preview
env:
  ENABLE_PDF_EXPORT: 1
  PYTHON_VERSION: "3.12"
permissions:
  contents: write
on:
  pull_request:
jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
            enable-cache: true

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Install Dependencies
        run: uv sync

      - name: Build and Deploy Preview
        env:
          VERSION: v.PR-${{ github.event.number }}
        run: |
          git config user.name jr-hms
          git config user.email jonas.rieger@analytical-software.de
          git fetch --no-tags --prune --depth=1 origin gh-pages-preview
          uv run mike deploy $VERSION latest \
               --branch gh-pages-preview \
               --update-aliases \
               --push
